### ISSUE TITLE
Output cleanup

### ISSUE THREAD

**Issue by necrolyte2** [VDBWRAIR/ngs_mapper#219] opened 2016-03-25 02:06 UTC
The output from `runsample`/`runsamplesheet.sh` is a bit messy
You can see here that some of the things should probably get tossed into the main log file instead of being sent to the terminal

```
[training ZikaRun4]$ !186
RUNSAMPLEOPTIONS="-c new_config.yaml" runsamplesheet.sh RawData SampleSheet.tsv
Using 24 cpus
2016-03-24 15:41:51,260 -- INFO -- runsample       --- Starting VIROAF552 --- 
2016-03-24 15:41:51,260 -- INFO -- runsample       --- Using custom config from new_config.yaml ---
2016-03-24 15:41:51,260 -- INFO -- runsample       --- Starting VIROAF553 --- 
2016-03-24 15:41:51,261 -- INFO -- runsample       --- Using custom config from new_config.yaml ---


2016-03-24 17:42:42,914 -- INFO -- runsample       --- Finished VIROAF552 ---
2016-03-24 17:50:36,616 -- INFO -- runsample       --- Finished VIROAF553 ---
Using 24 cpus
2016-03-24 17:50:38,557 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/VIROAF552/qualdepth/VIROAF552.bam.qualdepth.CPC_0740_USAMRIID_10807bp.png Projects/VIROAF552/VIROAF552.bam.qualdepth.png
2016-03-24 17:50:38,584 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/VIROAF553/qualdepth/VIROAF553.bam.qualdepth.CPC_0740_USAMRIID_10807bp.png Projects/VIROAF553/VIROAF553.bam.qualdepth.png

real	0m2.074s
user	0m2.019s
sys	0m0.113s

real	0m2.102s
user	0m2.062s
sys	0m0.093s
Reflen: 10808
Curregion: [10803, 10808, 'LowCoverage']
Reflen: 10808
Curregion: [9, 10803, 'Normal']
Creating new gap region to cover end of reference: [10803, 10808, 'Gap']
convert: DelegateLibrarySupportNotBuiltIn `QualDepth.pdf' (JPEG) @ error/pdf.c/WritePDFImage/1470.
2016-03-24 17:50:41,490 -- INFO -- graph_times     Plotting all projects inside of Projects
```

**Comment by averagehat** [comment] 2016-03-30 15:11
This is sort of a duplicate of #206.

**Closed** 2016-03-30 15:11 UTC
